version: 2

project_name: gogchat

before:
  hooks:
    - go mod tidy

builds:
  - id: gogchat
    main: ./cmd/gogchat
    binary: gogchat
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'github.com/cipher-shad0w/gogchat/internal/cmd.Version={{.Version}}'
      - -X 'github.com/cipher-shad0w/gogchat/internal/auth.DefaultClientID={{.Env.GOGCHAT_CLIENT_ID}}'
      - -X 'github.com/cipher-shad0w/gogchat/internal/auth.DefaultClientSecret={{.Env.GOGCHAT_CLIENT_SECRET}}'
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - repository:
      owner: cipher-shad0w
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/cipher-shad0w/gogchat"
    description: "A CLI for the Google Chat API"
    license: "MIT"
    install: |
      bin.install "gogchat"
    test: |
      system "#{bin}/gogchat", "--version"
